FROM python:3.12-slim-bookworm

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
# Set the working directory inside the container
WORKDIR /API

# Copy your application code into the container
COPY requirements.txt .
# Install Python dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the Celery worker with logging
CMD ["fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]
